import os
import pickle
import lmdb
import numpy as np
from tqdm import tqdm

def read_lmdb(lmdb_path):
    """
    读取 LMDB 文件并返回数据列表
    """
    if not os.path.exists(lmdb_path):
        raise FileNotFoundError(f"未找到文件: {lmdb_path}")

    print(f"正在读取 LMDB: {lmdb_path} ...")
    env = lmdb.open(
        lmdb_path,
        subdir=False,
        readonly=True,
        lock=False,
        readahead=False,
        meminit=False,
        max_readers=256,
    )
    txn = env.begin()
    keys = list(txn.cursor().iternext(values=False))

    out_list = []
    for idx in tqdm(keys, desc="Loading Data"):
        datapoint_pickled = txn.get(idx)
        data = pickle.loads(datapoint_pickled)
        out_list.append(data)

    env.close()
    return out_list

def write_pdb(atoms, coords, output_path, pocket_name="POCKET"):
    """
    将原子和坐标写入 PDB 格式文件
    注意：由于 LMDB 可能不包含残基信息，所有原子将被归为 'UNK' 残基
    """
    with open(output_path, 'w') as f:
        f.write(f"REMARK    GENERATED BY DRUGCLIP CONVERTER\n")
        f.write(f"REMARK    POCKET NAME: {pocket_name}\n")

        for i, (atom_type, (x, y, z)) in enumerate(zip(atoms, coords)):
            # PDB 原子行格式严格对齐
            # Record Name (6s) | Serial (5d) | (1s) | Atom Name (4s) | AltLoc (1s) | ResName (3s) | ...
            # 这里的 Atom Name 使用元素符号，ResName 设为 UNK (Unknown)

            # 确保原子类型是字符串
            if isinstance(atom_type,  (np.str_, str)):
                element = atom_type
            else:
                # 处理可能的编码情况
                element = str(atom_type)

            # 简单的原子名称处理 (例如 C ->  C  )
            atom_name = f" {element[:3]}".ljust(4)

            line = (
                f"ATOM  {i+1:5d} {atom_name} UNK A   1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           {element[:2].upper():>2}\n"
            )
            f.write(line)

        f.write("END\n")

def convert_all_pockets(lmdb_path, output_dir):
    """
    主转换函数
    """
    # 1. 读取数据
    data_list = read_lmdb(lmdb_path)

    # 2. 创建输出目录
    os.makedirs(output_dir, exist_ok=True)
    print(f"转换后的 PDB 文件将保存至: {output_dir}")

    # 3. 批量转换
    success_count = 0
    for data in tqdm(data_list, desc="Converting to PDB"):
        try:
            # 获取关键字段，根据你的数据结构调整键名
            # DrugCLIP 通常使用 'pocket' 作为 ID，'pocket_atoms' 和 'pocket_coordinates' 作为数据
            name = data.get("pocket", f"pocket_{success_count}")
            atoms = data.get("pocket_atoms")
            coords = data.get("pocket_coordinates")

            # 数据完整性检查
            if atoms is None or coords is None:
                print(f"跳过 {name}: 缺少原子或坐标数据")
                continue

            if len(atoms) != len(coords):
                print(f"跳过 {name}: 原子数 ({len(atoms)}) 与 坐标数 ({len(coords)}) 不匹配")
                continue

            # 构建文件名 (清理非法字符)
            clean_name = str(name).replace("/", "_").replace("\\", "_")
            save_path = os.path.join(output_dir, f"{clean_name}.pdb")

            # 写入 PDB
            write_pdb(atoms, coords, save_path, pocket_name=clean_name)
            success_count += 1

        except Exception as e:
            print(f"转换 {name} 时出错: {e}")

    print(f"\n转换完成！成功生成 {success_count} 个 PDB 文件。")
    print(f"请使用 PyMOL 打开 {output_dir} 查看口袋结构。")

if __name__ == "__main__":
    # ================= 配置区域 =================
    # 输入：你的 pocket.lmdb 路径
    INPUT_LMDB = "/mnt/e/Workspace/260217-DrugClip/files/retrieval/pocket.lmdb"

    # 输出：你想保存 PDB 文件的文件夹
    OUTPUT_DIR = "/mnt/e/Workspace/260217-DrugClip/files/retrieval/converted_pockets"
    # ===========================================

    convert_all_pockets(INPUT_LMDB, OUTPUT_DIR)
